services:
  - type: web
    name: cv-analyser
    env: python
    plan: free
    region: oregon
    buildCommand: "pip install -r deploy-requirements.txt"
    startCommand: "gunicorn --bind 0.0.0.0:$PORT app:app"
    envVars:
      - key: GEMINI_API_KEY
        sync: false
    autoDeploy: true
    healthCheckPath: /
